baseURL = 'https://zhangrayhung.github.io/'
languageCode = 'en-us'
title = 'YEKAIHONGXUE'
theme = "paper"

[params]
  # home page profile
  avatar = 'zhangrayhung@gmail.com'
  name = 'YEKAIHONGXUE'
  bio = 'Yekai is on the left and Hongxue is on the right'

  fancybox = true

  # enable Giscus(Github discussion), https://github.com/apps/giscus, https://giscus.app/
  [params.giscus]
    enable = true
    repo = "zhangrayhung/hugo-comments"
    repoId = "R_kgDOQMBS-g"
    category = "Announcements"
    categoryId = "DIC_kwDOQMBS-s4CxQEL"
    mapping = "pathname"
    theme = "preferred_color_scheme"

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 1